server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: harshu20

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

